import { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";


const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "500"],
});

export const metadata: Metadata = {
  title: "Auth login",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} antialiased `}>
      
      {children}
    </div>
  );
}