import { Metadata } from "next";
import { Geist } from "next/font/google";
import "../globals.css";
import Header from "@/components/header";

const geist = Geist({
  subsets: ["latin"],
  weight: ["100", "200", "500"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${geist.className} antialiased`}>
      <Header />
      {children}
    </div>
  );
}